---
language: java
jdk:
  - oraclejdk8
env:
  - SCRIPT=bin/unit-tests.sh
 
  # https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines
  - SCRIPT="bin/build-jq.sh;
      for file in \`curl -s https://api.github.com/repos/exercism/java/pulls/$TRAVIS_PULL_REQUEST/files | bin/jq -r '.[].filename'\`;
      do if [[ \$file == exercises* ]] || [[ \$file == config.json ]];
        then rvm install 2.2.5;
        rvm use 2.2.5;
        bin/journey-tests.sh;
        break;
      fi;
    done"

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

addons:
  apt:
    packages:
      - tree

# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true  # if we don't skip install, ./gradlew assemble is invoked, but this task is not available.

before_script:
  - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH  # ensure our tools are prefered over included ones.

script:
  - eval $SCRIPT

# configure caching (https://docs.travis-ci.com/user/languages/java/#Caching)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# format from https://docs.travis-ci.com/user/caching/#Enabling-multiple-caching-features
cache:
  bundler: true
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a8514b96052a7155b59
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
