name: Deprecated

on:
  pull_request:
    paths:
      - "exercises/**"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-deprecated:
    name: Check for deprecated exercises
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
      - name: Test deprecated exercises using test-deprecated-exercises
        run: bin/test-deprecated-exercises
