# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Set up JDK 1.17
      uses: actions/setup-java@19eeec562b37d29a1ad055b7de9c280bd0906d8d
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and checkstyle with Gradle
      run: cd exercises && ../gradlew check compileStarterSourceJava --parallel --continue --info

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - name: Set up JDK 1.17
      uses: actions/setup-java@19eeec562b37d29a1ad055b7de9c280bd0906d8d
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Journey test
      run: bin/journey-test.sh
