# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: Set up JDK 1.17
      uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile and checkstyle with Gradle
      run: cd exercises && ../gradlew check compileStarterSourceJava --parallel --continue --info

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: Set up JDK 1.17
      uses: actions/setup-java@c3ac5dd0ed8db40fedb61c32fbe677e6b355e94c
      with:
        java-version: 17
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Journey test
      run: bin/journey-test.sh
